2022-04-12 18:43:14.204 +07 [1594] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 18:43:14.205 +07 [1594] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 18:43:14.206 +07 [1594] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 18:43:14.284 +07 [1594] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 18:43:14.293 +07 [1597] LOG:  database system was shut down at 2022-04-12 18:43:11 +07
2022-04-12 18:43:14.333 +07 [1594] LOG:  database system is ready to accept connections
2022-04-12 18:45:20.568 +07 [1842] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 18:45:20.569 +07 [1842] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 18:45:20.570 +07 [1842] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 18:45:20.577 +07 [1842] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 18:45:20.592 +07 [1845] LOG:  database system was interrupted; last known up at 2022-04-12 18:43:14 +07
2022-04-12 18:45:21.107 +07 [1845] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 18:45:21.127 +07 [1845] LOG:  redo starts at 0/14FEE50
2022-04-12 18:45:21.130 +07 [1845] LOG:  invalid record length at 0/1526900: wanted 24, got 0
2022-04-12 18:45:21.130 +07 [1845] LOG:  redo done at 0/15268C8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.01 s
2022-04-12 18:45:21.137 +07 [1843] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 18:45:21.187 +07 [1843] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.016 s, sync=0.024 s, total=0.053 s; sync files=28, longest=0.009 s, average=0.001 s; distance=158 kB, estimate=158 kB
2022-04-12 18:45:21.193 +07 [1842] LOG:  database system is ready to accept connections
2022-04-12 18:45:21.263 +07 [1850] ERROR:  relation "t2" already exists
2022-04-12 18:45:21.263 +07 [1850] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 18:45:21.279 +07 [1852] ERROR:  relation "t3" already exists
2022-04-12 18:45:21.279 +07 [1852] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 18:45:21.298 +07 [1854] ERROR:  relation "t4" already exists
2022-04-12 18:45:21.298 +07 [1854] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 18:45:21.315 +07 [1856] ERROR:  relation "t12" already exists
2022-04-12 18:45:21.315 +07 [1856] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 18:48:25.725 +07 [1970] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 18:48:25.726 +07 [1970] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 18:48:25.726 +07 [1970] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 18:48:25.738 +07 [1970] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 18:48:25.748 +07 [1973] LOG:  database system was interrupted; last known up at 2022-04-12 18:45:21 +07
2022-04-12 18:48:26.279 +07 [1973] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 18:48:26.284 +07 [1973] LOG:  redo starts at 0/1526978
2022-04-12 18:48:26.284 +07 [1973] LOG:  invalid record length at 0/15269B0: wanted 24, got 0
2022-04-12 18:48:26.284 +07 [1973] LOG:  redo done at 0/1526978 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 18:48:26.291 +07 [1971] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 18:48:26.310 +07 [1971] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.022 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 18:48:26.323 +07 [1970] LOG:  database system is ready to accept connections
2022-04-12 18:48:26.437 +07 [1978] ERROR:  relation "t2" already exists
2022-04-12 18:48:26.437 +07 [1978] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 18:48:26.454 +07 [1980] ERROR:  relation "t3" already exists
2022-04-12 18:48:26.454 +07 [1980] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 18:48:26.470 +07 [1982] ERROR:  relation "t4" already exists
2022-04-12 18:48:26.470 +07 [1982] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 18:48:26.495 +07 [1984] ERROR:  relation "t12" already exists
2022-04-12 18:48:26.495 +07 [1984] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:09:08.279 +07 [2073] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:09:08.280 +07 [2073] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:09:08.280 +07 [2073] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:09:08.286 +07 [2073] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:09:08.300 +07 [2076] LOG:  database system was interrupted; last known up at 2022-04-12 18:48:26 +07
2022-04-12 19:09:08.825 +07 [2076] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:09:08.830 +07 [2076] LOG:  redo starts at 0/1526A28
2022-04-12 19:09:08.830 +07 [2076] LOG:  invalid record length at 0/1526A60: wanted 24, got 0
2022-04-12 19:09:08.830 +07 [2076] LOG:  redo done at 0/1526A28 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:09:08.839 +07 [2074] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:09:08.856 +07 [2074] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.002 s, total=0.021 s; sync files=2, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
2022-04-12 19:09:08.864 +07 [2073] LOG:  database system is ready to accept connections
2022-04-12 19:09:09.027 +07 [2081] ERROR:  relation "t2" already exists
2022-04-12 19:09:09.027 +07 [2081] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:09:09.047 +07 [2083] ERROR:  relation "t3" already exists
2022-04-12 19:09:09.047 +07 [2083] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:09:09.063 +07 [2085] ERROR:  relation "t4" already exists
2022-04-12 19:09:09.063 +07 [2085] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:09:09.080 +07 [2087] ERROR:  relation "t12" already exists
2022-04-12 19:09:09.080 +07 [2087] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:27:41.528 +07 [2227] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:27:41.529 +07 [2227] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:27:41.529 +07 [2227] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:27:41.535 +07 [2227] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:27:41.545 +07 [2230] LOG:  database system was interrupted; last known up at 2022-04-12 19:09:08 +07
2022-04-12 19:27:42.097 +07 [2230] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:27:42.102 +07 [2230] LOG:  redo starts at 0/1526AD8
2022-04-12 19:27:42.102 +07 [2230] LOG:  invalid record length at 0/1526B10: wanted 24, got 0
2022-04-12 19:27:42.102 +07 [2230] LOG:  redo done at 0/1526AD8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:27:42.111 +07 [2228] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:27:42.131 +07 [2228] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.003 s, total=0.023 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:27:42.137 +07 [2227] LOG:  database system is ready to accept connections
2022-04-12 19:27:42.302 +07 [2235] ERROR:  relation "t2" already exists
2022-04-12 19:27:42.302 +07 [2235] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:27:42.317 +07 [2237] ERROR:  relation "t3" already exists
2022-04-12 19:27:42.317 +07 [2237] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:27:42.333 +07 [2239] ERROR:  relation "t4" already exists
2022-04-12 19:27:42.333 +07 [2239] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:27:42.352 +07 [2241] ERROR:  relation "t12" already exists
2022-04-12 19:27:42.352 +07 [2241] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:27:42.688 +07 [2243] ERROR:  syntax error at or near "FROM" at character 18
2022-04-12 19:27:42.688 +07 [2243] STATEMENT:  COPY (SELECT (a, FROM public.t2 ) TO stdout;
2022-04-12 19:27:43.001 +07 [2245] ERROR:  syntax error at or near "FROM" at character 18
2022-04-12 19:27:43.001 +07 [2245] STATEMENT:  COPY (SELECT (a, FROM public.t3 ) TO stdout;
2022-04-12 19:31:06.683 +07 [2293] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:31:06.684 +07 [2293] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:31:06.684 +07 [2293] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:31:06.691 +07 [2293] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:31:06.705 +07 [2296] LOG:  database system was interrupted; last known up at 2022-04-12 19:27:42 +07
2022-04-12 19:31:07.218 +07 [2296] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:31:07.239 +07 [2296] LOG:  redo starts at 0/1526B88
2022-04-12 19:31:07.240 +07 [2296] LOG:  invalid record length at 0/1526BC0: wanted 24, got 0
2022-04-12 19:31:07.240 +07 [2296] LOG:  redo done at 0/1526B88 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:31:07.247 +07 [2294] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:31:07.306 +07 [2294] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.027 s, total=0.062 s; sync files=2, longest=0.017 s, average=0.014 s; distance=0 kB, estimate=0 kB
2022-04-12 19:31:07.312 +07 [2293] LOG:  database system is ready to accept connections
2022-04-12 19:31:07.382 +07 [2301] ERROR:  relation "t2" already exists
2022-04-12 19:31:07.382 +07 [2301] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:31:07.397 +07 [2303] ERROR:  relation "t3" already exists
2022-04-12 19:31:07.397 +07 [2303] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:31:07.417 +07 [2305] ERROR:  relation "t4" already exists
2022-04-12 19:31:07.417 +07 [2305] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:31:07.433 +07 [2307] ERROR:  relation "t12" already exists
2022-04-12 19:31:07.433 +07 [2307] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:32:43.375 +07 [2351] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:32:43.376 +07 [2351] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:32:43.377 +07 [2351] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:32:43.383 +07 [2351] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:32:43.397 +07 [2354] LOG:  database system was interrupted; last known up at 2022-04-12 19:31:07 +07
2022-04-12 19:32:43.923 +07 [2354] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:32:43.928 +07 [2354] LOG:  redo starts at 0/1526C38
2022-04-12 19:32:43.928 +07 [2354] LOG:  invalid record length at 0/1526C70: wanted 24, got 0
2022-04-12 19:32:43.928 +07 [2354] LOG:  redo done at 0/1526C38 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:32:43.935 +07 [2352] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:32:43.955 +07 [2352] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.003 s, total=0.023 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:32:43.962 +07 [2351] LOG:  database system is ready to accept connections
2022-04-12 19:32:44.097 +07 [2359] ERROR:  relation "t2" already exists
2022-04-12 19:32:44.097 +07 [2359] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:32:44.112 +07 [2361] ERROR:  relation "t3" already exists
2022-04-12 19:32:44.112 +07 [2361] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:32:44.129 +07 [2363] ERROR:  relation "t4" already exists
2022-04-12 19:32:44.129 +07 [2363] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:32:44.148 +07 [2365] ERROR:  relation "t12" already exists
2022-04-12 19:32:44.148 +07 [2365] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:32:44.763 +07 [2367] LOG:  unexpected EOF on client connection with an open transaction
2022-04-12 19:32:45.398 +07 [2376] LOG:  unexpected EOF on client connection with an open transaction
2022-04-12 19:34:18.814 +07 [2446] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:34:18.816 +07 [2446] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:34:18.817 +07 [2446] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:34:18.822 +07 [2446] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:34:18.834 +07 [2449] LOG:  database system was interrupted; last known up at 2022-04-12 19:32:43 +07
2022-04-12 19:34:19.351 +07 [2449] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:34:19.356 +07 [2449] LOG:  redo starts at 0/1526CE8
2022-04-12 19:34:19.356 +07 [2449] LOG:  invalid record length at 0/1526D20: wanted 24, got 0
2022-04-12 19:34:19.356 +07 [2449] LOG:  redo done at 0/1526CE8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:34:19.364 +07 [2447] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:34:19.381 +07 [2447] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.003 s, total=0.021 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:34:19.386 +07 [2446] LOG:  database system is ready to accept connections
2022-04-12 19:34:19.521 +07 [2454] ERROR:  relation "t2" already exists
2022-04-12 19:34:19.521 +07 [2454] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:34:19.540 +07 [2456] ERROR:  relation "t3" already exists
2022-04-12 19:34:19.540 +07 [2456] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:34:19.557 +07 [2458] ERROR:  relation "t4" already exists
2022-04-12 19:34:19.557 +07 [2458] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:34:19.575 +07 [2460] ERROR:  relation "t12" already exists
2022-04-12 19:34:19.575 +07 [2460] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:34:19.902 +07 [2462] ERROR:  syntax error at or near "FROM" at character 18
2022-04-12 19:34:19.902 +07 [2462] STATEMENT:  COPY (SELECT (a, FROM public.t2 ) TO stdout;
2022-04-12 19:34:20.220 +07 [2464] ERROR:  syntax error at or near "FROM" at character 18
2022-04-12 19:34:20.220 +07 [2464] STATEMENT:  COPY (SELECT (a, FROM public.t3 ) TO stdout;
2022-04-12 19:35:37.587 +07 [2504] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:35:37.589 +07 [2504] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:35:37.589 +07 [2504] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:35:37.597 +07 [2504] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:35:37.608 +07 [2507] LOG:  database system was interrupted; last known up at 2022-04-12 19:34:19 +07
2022-04-12 19:35:38.122 +07 [2507] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:35:38.126 +07 [2507] LOG:  redo starts at 0/1526D98
2022-04-12 19:35:38.126 +07 [2507] LOG:  invalid record length at 0/1526DD0: wanted 24, got 0
2022-04-12 19:35:38.126 +07 [2507] LOG:  redo done at 0/1526D98 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:35:38.134 +07 [2505] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:35:38.177 +07 [2505] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.028 s, total=0.046 s; sync files=2, longest=0.017 s, average=0.014 s; distance=0 kB, estimate=0 kB
2022-04-12 19:35:38.183 +07 [2504] LOG:  database system is ready to accept connections
2022-04-12 19:35:38.300 +07 [2512] ERROR:  relation "t2" already exists
2022-04-12 19:35:38.300 +07 [2512] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:35:38.317 +07 [2514] ERROR:  relation "t3" already exists
2022-04-12 19:35:38.317 +07 [2514] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:35:38.332 +07 [2516] ERROR:  relation "t4" already exists
2022-04-12 19:35:38.332 +07 [2516] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:35:38.350 +07 [2518] ERROR:  relation "t12" already exists
2022-04-12 19:35:38.350 +07 [2518] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:36:15.048 +07 [2558] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:36:15.049 +07 [2558] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:36:15.049 +07 [2558] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:36:15.059 +07 [2558] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:36:15.101 +07 [2561] LOG:  database system was interrupted; last known up at 2022-04-12 19:35:38 +07
2022-04-12 19:36:15.849 +07 [2561] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:36:15.855 +07 [2561] LOG:  redo starts at 0/1526E48
2022-04-12 19:36:15.855 +07 [2561] LOG:  invalid record length at 0/1526E80: wanted 24, got 0
2022-04-12 19:36:15.855 +07 [2561] LOG:  redo done at 0/1526E48 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:36:15.865 +07 [2559] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:36:15.889 +07 [2559] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.003 s, total=0.028 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:36:15.895 +07 [2558] LOG:  database system is ready to accept connections
2022-04-12 19:36:15.940 +07 [2566] ERROR:  relation "t2" already exists
2022-04-12 19:36:15.940 +07 [2566] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:36:15.956 +07 [2568] ERROR:  relation "t3" already exists
2022-04-12 19:36:15.956 +07 [2568] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:36:15.982 +07 [2570] ERROR:  relation "t4" already exists
2022-04-12 19:36:15.982 +07 [2570] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:36:16.003 +07 [2572] ERROR:  relation "t12" already exists
2022-04-12 19:36:16.003 +07 [2572] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:36:51.949 +07 [2612] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:36:51.950 +07 [2612] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:36:51.950 +07 [2612] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:36:51.959 +07 [2612] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:36:51.972 +07 [2615] LOG:  database system was interrupted; last known up at 2022-04-12 19:36:15 +07
2022-04-12 19:36:52.483 +07 [2615] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:36:52.487 +07 [2615] LOG:  redo starts at 0/1526EF8
2022-04-12 19:36:52.487 +07 [2615] LOG:  invalid record length at 0/1526F30: wanted 24, got 0
2022-04-12 19:36:52.487 +07 [2615] LOG:  redo done at 0/1526EF8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:36:52.496 +07 [2613] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:36:52.539 +07 [2613] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.003 s, total=0.045 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:36:52.545 +07 [2612] LOG:  database system is ready to accept connections
2022-04-12 19:36:52.671 +07 [2620] ERROR:  relation "t2" already exists
2022-04-12 19:36:52.671 +07 [2620] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:36:52.693 +07 [2622] ERROR:  relation "t3" already exists
2022-04-12 19:36:52.693 +07 [2622] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:36:52.710 +07 [2624] ERROR:  relation "t4" already exists
2022-04-12 19:36:52.710 +07 [2624] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:36:52.727 +07 [2626] ERROR:  relation "t12" already exists
2022-04-12 19:36:52.727 +07 [2626] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:36:53.284 +07 [2628] LOG:  unexpected EOF on client connection with an open transaction
2022-04-12 19:36:53.838 +07 [2637] LOG:  unexpected EOF on client connection with an open transaction
2022-04-12 19:37:50.540 +07 [2680] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:37:50.541 +07 [2680] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:37:50.541 +07 [2680] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:37:50.549 +07 [2680] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:37:50.558 +07 [2683] LOG:  database system was interrupted; last known up at 2022-04-12 19:36:52 +07
2022-04-12 19:37:51.065 +07 [2683] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:37:51.069 +07 [2683] LOG:  redo starts at 0/1526FA8
2022-04-12 19:37:51.069 +07 [2683] LOG:  invalid record length at 0/1526FE0: wanted 24, got 0
2022-04-12 19:37:51.069 +07 [2683] LOG:  redo done at 0/1526FA8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:37:51.077 +07 [2681] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:37:51.094 +07 [2681] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.021 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:37:51.100 +07 [2680] LOG:  database system is ready to accept connections
2022-04-12 19:37:51.238 +07 [2688] ERROR:  relation "t2" already exists
2022-04-12 19:37:51.238 +07 [2688] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:37:51.252 +07 [2690] ERROR:  relation "t3" already exists
2022-04-12 19:37:51.252 +07 [2690] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:37:51.271 +07 [2692] ERROR:  relation "t4" already exists
2022-04-12 19:37:51.271 +07 [2692] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:37:51.285 +07 [2694] ERROR:  relation "t12" already exists
2022-04-12 19:37:51.285 +07 [2694] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:38:23.897 +07 [2735] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:38:23.898 +07 [2735] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:38:23.898 +07 [2735] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:38:23.906 +07 [2735] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:38:23.919 +07 [2738] LOG:  database system was interrupted; last known up at 2022-04-12 19:37:51 +07
2022-04-12 19:38:24.426 +07 [2738] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:38:24.448 +07 [2738] LOG:  redo starts at 0/1527058
2022-04-12 19:38:24.448 +07 [2738] LOG:  invalid record length at 0/1527090: wanted 24, got 0
2022-04-12 19:38:24.448 +07 [2738] LOG:  redo done at 0/1527058 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:38:24.456 +07 [2736] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:38:24.473 +07 [2736] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.002 s, total=0.020 s; sync files=2, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
2022-04-12 19:38:24.477 +07 [2735] LOG:  database system is ready to accept connections
2022-04-12 19:38:24.584 +07 [2743] ERROR:  relation "t2" already exists
2022-04-12 19:38:24.584 +07 [2743] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:38:24.598 +07 [2745] ERROR:  relation "t3" already exists
2022-04-12 19:38:24.598 +07 [2745] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:38:24.619 +07 [2747] ERROR:  relation "t4" already exists
2022-04-12 19:38:24.619 +07 [2747] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:38:24.635 +07 [2749] ERROR:  relation "t12" already exists
2022-04-12 19:38:24.635 +07 [2749] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:47:04.836 +07 [2821] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:47:04.837 +07 [2821] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:47:04.838 +07 [2821] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:47:04.843 +07 [2821] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:47:04.858 +07 [2824] LOG:  database system was interrupted; last known up at 2022-04-12 19:38:24 +07
2022-04-12 19:47:05.379 +07 [2824] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:47:05.383 +07 [2824] LOG:  redo starts at 0/1527108
2022-04-12 19:47:05.383 +07 [2824] LOG:  invalid record length at 0/1527140: wanted 24, got 0
2022-04-12 19:47:05.383 +07 [2824] LOG:  redo done at 0/1527108 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:47:05.391 +07 [2822] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:47:05.409 +07 [2822] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.020 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:47:05.415 +07 [2821] LOG:  database system is ready to accept connections
2022-04-12 19:47:05.586 +07 [2829] ERROR:  relation "t2" already exists
2022-04-12 19:47:05.586 +07 [2829] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:47:05.607 +07 [2831] ERROR:  relation "t3" already exists
2022-04-12 19:47:05.607 +07 [2831] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:47:05.631 +07 [2833] ERROR:  relation "t4" already exists
2022-04-12 19:47:05.631 +07 [2833] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:47:05.657 +07 [2835] ERROR:  relation "t12" already exists
2022-04-12 19:47:05.657 +07 [2835] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:47:05.983 +07 [2837] ERROR:  function function(integer) does not exist at character 17
2022-04-12 19:47:05.983 +07 [2837] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-12 19:47:05.983 +07 [2837] STATEMENT:  COPY (SELECT a, function(a) , function(b) , function(c) FROM public.t2 ) TO stdout;
2022-04-12 19:47:06.294 +07 [2839] ERROR:  syntax error at or near "." at character 61
2022-04-12 19:47:06.294 +07 [2839] STATEMENT:  COPY (SELECT a, function(a) , function(b) , c, idFROM public.t3 ) TO stdout;
2022-04-12 19:52:55.173 +07 [2889] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:52:55.174 +07 [2889] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:52:55.174 +07 [2889] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:52:55.300 +07 [2889] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:52:55.308 +07 [2892] LOG:  database system was interrupted; last known up at 2022-04-12 19:47:05 +07
2022-04-12 19:52:55.851 +07 [2892] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:52:55.855 +07 [2892] LOG:  redo starts at 0/15271B8
2022-04-12 19:52:55.855 +07 [2892] LOG:  invalid record length at 0/15271F0: wanted 24, got 0
2022-04-12 19:52:55.855 +07 [2892] LOG:  redo done at 0/15271B8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:52:55.862 +07 [2890] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:52:55.882 +07 [2890] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.023 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:52:55.888 +07 [2889] LOG:  database system is ready to accept connections
2022-04-12 19:52:55.972 +07 [2897] ERROR:  relation "t2" already exists
2022-04-12 19:52:55.972 +07 [2897] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:52:55.999 +07 [2899] ERROR:  relation "t3" already exists
2022-04-12 19:52:55.999 +07 [2899] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:52:56.017 +07 [2901] ERROR:  relation "t4" already exists
2022-04-12 19:52:56.017 +07 [2901] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:52:56.033 +07 [2903] ERROR:  relation "t12" already exists
2022-04-12 19:52:56.033 +07 [2903] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:52:56.356 +07 [2905] ERROR:  syntax error at or near "public" at character 55
2022-04-12 19:52:56.356 +07 [2905] STATEMENT:  COPY (SELECT function(a), function(b), function(cFROM public.t2 ) TO stdout;
2022-04-12 19:52:56.666 +07 [2907] ERROR:  syntax error at or near "," at character 40
2022-04-12 19:52:56.666 +07 [2907] STATEMENT:  COPY (SELECT function(a), function(b), , c, , idFROM public.t3 ) TO stdout;
2022-04-12 19:55:10.784 +07 [2953] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 19:55:10.788 +07 [2953] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 19:55:10.788 +07 [2953] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 19:55:10.797 +07 [2953] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 19:55:10.806 +07 [2956] LOG:  database system was interrupted; last known up at 2022-04-12 19:52:55 +07
2022-04-12 19:55:11.317 +07 [2956] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 19:55:11.321 +07 [2956] LOG:  redo starts at 0/1527268
2022-04-12 19:55:11.321 +07 [2956] LOG:  invalid record length at 0/15272A0: wanted 24, got 0
2022-04-12 19:55:11.321 +07 [2956] LOG:  redo done at 0/1527268 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 19:55:11.328 +07 [2954] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 19:55:11.350 +07 [2954] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.003 s, total=0.025 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 19:55:11.354 +07 [2953] LOG:  database system is ready to accept connections
2022-04-12 19:55:11.504 +07 [2961] ERROR:  relation "t2" already exists
2022-04-12 19:55:11.504 +07 [2961] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 19:55:11.521 +07 [2963] ERROR:  relation "t3" already exists
2022-04-12 19:55:11.521 +07 [2963] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 19:55:11.538 +07 [2965] ERROR:  relation "t4" already exists
2022-04-12 19:55:11.538 +07 [2965] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 19:55:11.559 +07 [2967] ERROR:  relation "t12" already exists
2022-04-12 19:55:11.559 +07 [2967] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 19:55:11.893 +07 [2969] ERROR:  function function(integer) does not exist at character 14
2022-04-12 19:55:11.893 +07 [2969] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-12 19:55:11.893 +07 [2969] STATEMENT:  COPY (SELECT function(a), function(b), function(c) FROM public.t2 ) TO stdout;
2022-04-12 19:55:12.203 +07 [2971] ERROR:  syntax error at or near "," at character 40
2022-04-12 19:55:12.203 +07 [2971] STATEMENT:  COPY (SELECT function(a), function(b), , c, , id FROM public.t3 ) TO stdout;
2022-04-12 20:01:08.113 +07 [3098] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 20:01:08.114 +07 [3098] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 20:01:08.114 +07 [3098] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 20:01:08.121 +07 [3098] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 20:01:08.131 +07 [3101] LOG:  database system was interrupted; last known up at 2022-04-12 19:55:11 +07
2022-04-12 20:01:08.661 +07 [3101] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 20:01:08.669 +07 [3101] LOG:  redo starts at 0/1527318
2022-04-12 20:01:08.669 +07 [3101] LOG:  invalid record length at 0/1527350: wanted 24, got 0
2022-04-12 20:01:08.669 +07 [3101] LOG:  redo done at 0/1527318 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 20:01:08.677 +07 [3099] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 20:01:08.698 +07 [3099] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.024 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 20:01:08.704 +07 [3098] LOG:  database system is ready to accept connections
2022-04-12 20:01:08.852 +07 [3106] ERROR:  relation "t2" already exists
2022-04-12 20:01:08.852 +07 [3106] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 20:01:08.866 +07 [3108] ERROR:  relation "t3" already exists
2022-04-12 20:01:08.866 +07 [3108] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 20:01:08.885 +07 [3110] ERROR:  relation "t4" already exists
2022-04-12 20:01:08.885 +07 [3110] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 20:01:08.904 +07 [3112] ERROR:  relation "t12" already exists
2022-04-12 20:01:08.904 +07 [3112] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 20:01:09.223 +07 [3114] ERROR:  function function(integer) does not exist at character 14
2022-04-12 20:01:09.223 +07 [3114] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-12 20:01:09.223 +07 [3114] STATEMENT:  COPY (SELECT function(a), function(b), function(c) FROM public.t2 ) TO stdout;
2022-04-12 20:01:09.532 +07 [3116] ERROR:  syntax error at or near "," at character 40
2022-04-12 20:01:09.532 +07 [3116] STATEMENT:  COPY (SELECT function(a), function(b), , c, , id FROM public.t3 ) TO stdout;
2022-04-12 20:03:06.107 +07 [3157] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 20:03:06.108 +07 [3157] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 20:03:06.108 +07 [3157] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 20:03:06.114 +07 [3157] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 20:03:06.122 +07 [3160] LOG:  database system was interrupted; last known up at 2022-04-12 20:01:08 +07
2022-04-12 20:03:06.695 +07 [3160] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 20:03:06.701 +07 [3160] LOG:  redo starts at 0/15273C8
2022-04-12 20:03:06.701 +07 [3160] LOG:  invalid record length at 0/1527400: wanted 24, got 0
2022-04-12 20:03:06.701 +07 [3160] LOG:  redo done at 0/15273C8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 20:03:06.709 +07 [3158] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 20:03:06.770 +07 [3158] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.028 s, total=0.064 s; sync files=2, longest=0.017 s, average=0.014 s; distance=0 kB, estimate=0 kB
2022-04-12 20:03:06.775 +07 [3157] LOG:  database system is ready to accept connections
2022-04-12 20:03:06.877 +07 [3165] ERROR:  relation "t2" already exists
2022-04-12 20:03:06.877 +07 [3165] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 20:03:06.895 +07 [3167] ERROR:  relation "t3" already exists
2022-04-12 20:03:06.895 +07 [3167] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 20:03:06.916 +07 [3169] ERROR:  relation "t4" already exists
2022-04-12 20:03:06.916 +07 [3169] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 20:03:06.940 +07 [3171] ERROR:  relation "t12" already exists
2022-04-12 20:03:06.940 +07 [3171] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 20:03:07.370 +07 [3173] ERROR:  function function(integer) does not exist at character 14
2022-04-12 20:03:07.370 +07 [3173] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-12 20:03:07.370 +07 [3173] STATEMENT:  COPY (SELECT function(a), function(b), function(c) FROM public.t2 ) TO stdout;
2022-04-12 20:03:07.816 +07 [3175] ERROR:  syntax error at or near "," at character 40
2022-04-12 20:03:07.816 +07 [3175] STATEMENT:  COPY (SELECT function(a), function(b), , c, , id FROM public.t3 ) TO stdout;
2022-04-12 20:04:04.586 +07 [3211] LOG:  starting PostgreSQL 15devel on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-04-12 20:04:04.587 +07 [3211] LOG:  listening on IPv6 address "::1", port 5432
2022-04-12 20:04:04.587 +07 [3211] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-04-12 20:04:04.596 +07 [3211] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-04-12 20:04:04.603 +07 [3214] LOG:  database system was interrupted; last known up at 2022-04-12 20:03:06 +07
2022-04-12 20:04:05.147 +07 [3214] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-12 20:04:05.151 +07 [3214] LOG:  redo starts at 0/1527478
2022-04-12 20:04:05.151 +07 [3214] LOG:  invalid record length at 0/15274B0: wanted 24, got 0
2022-04-12 20:04:05.151 +07 [3214] LOG:  redo done at 0/1527478 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-04-12 20:04:05.159 +07 [3212] LOG:  checkpoint starting: end-of-recovery immediate wait
2022-04-12 20:04:05.211 +07 [3212] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.003 s, total=0.055 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
2022-04-12 20:04:05.217 +07 [3211] LOG:  database system is ready to accept connections
2022-04-12 20:04:05.261 +07 [3219] ERROR:  relation "t2" already exists
2022-04-12 20:04:05.261 +07 [3219] STATEMENT:  CREATE TABLE t2 (
					a	integer,
					b	integer,
					c	integer
	)
2022-04-12 20:04:05.281 +07 [3221] ERROR:  relation "t3" already exists
2022-04-12 20:04:05.281 +07 [3221] STATEMENT:  CREATE TABLE t3 (
					a	integer,
					b	integer,
					c	integer,
					id	integer
	)
2022-04-12 20:04:05.318 +07 [3223] ERROR:  relation "t4" already exists
2022-04-12 20:04:05.318 +07 [3223] STATEMENT:  CREATE TABLE t4 (
					id	integer
	)
2022-04-12 20:04:05.345 +07 [3225] ERROR:  relation "t12" already exists
2022-04-12 20:04:05.345 +07 [3225] STATEMENT:  CREATE TABLE t12 (
					id	integer,
					fio	varchar(40),
					salary	integer,
					adress	varchar(100)
	)
2022-04-12 20:04:05.705 +07 [3227] ERROR:  function function(integer) does not exist at character 14
2022-04-12 20:04:05.705 +07 [3227] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-12 20:04:05.705 +07 [3227] STATEMENT:  COPY (SELECT function(a), function(b), function(c) FROM public.t2 ) TO stdout;
2022-04-12 20:04:06.019 +07 [3230] ERROR:  function function(integer) does not exist at character 14
2022-04-12 20:04:06.019 +07 [3230] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2022-04-12 20:04:06.019 +07 [3230] STATEMENT:  COPY (SELECT function(a), function(b), c, id FROM public.t3 ) TO stdout;
